name: CD-edge
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: .\scripts\test.ps1
  lint:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: .\scripts\lint.ps1
  build-and-release:
    needs: [test, lint]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build pyinstaller
        run: |
         python -m pip install --upgrade pip
         git clone --depth 1 --branch v4.1 https://github.com/pyinstaller/pyinstaller
         cd .\pyinstaller\bootloader\
         python ./waf all
         cd ..
         python setup.py install
      - name: Build
        run: |
          pyinstaller --onefile src\main.py --name cyberpunk2077-usability --windowed --icon=logo.ico
          tar -c -f cyberpunk2077-usability.zip dist specs.md
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cyberpunk2077-usability.zip
          asset_name: cyberpunk2077-usability.zip
          tag: refs/heads/main
          overwrite: true