name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 30
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test
      run: .\scripts\test.ps1
  lint:
    timeout-minutes: 30
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Lint
        run: .\scripts\lint.ps1
  build:
    timeout-minutes: 30
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build pyinstaller
        run: |
          python -m pip install --upgrade pip
          git clone --depth 1 --branch v4.1 https://github.com/pyinstaller/pyinstaller
          cd .\pyinstaller\bootloader\
          python ./waf all
          cd ..
          python setup.py install
      - name: Build app
        id: build
        run: pyinstaller --onefile src\main.py --name ${{ github.event.repository.name }}-${{ github.sha }} --windowed --icon=logo.ico
      - name: Upload edge artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: dist