name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test
      run: .\scripts\test.ps1
  lint:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Lint
        run: .\scripts\lint.ps1
  build-dev:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build
        run: .\scripts\build.ps1 -env dev
      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: development
          path: dist
  build-edge:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build pyinstaller
        run: |
          python -m pip install --upgrade pip
          git clone --depth 1 --branch v4.1 https://github.com/pyinstaller/pyinstaller
          cd .\pyinstaller\bootloader\
          python ./waf all
          cd ..
          python setup.py install
      - name: Build
        run: pyinstaller --onefile src\main.py --name cyberpunk2077-usability --icon=logo.ico --console
      - name: Upload edge artifact
        uses: actions/upload-artifact@v2
        with:
          name: edge
          path: dist